### ISSUE TITLE
Navbar & Side Menu

### ISSUE THREAD

**Issue by shyjnnn** [LikeLion-at-DGU/2022_autumn_festival_front#10]
- Navbar 그림자 제거 완료

**Comment by shyjnnn** [comment]
- 메뉴 아이콘이 오른쪽 정렬이 안됩니다.
   -  margin, align 등 계속 수정해도 안되서 아시는 분 해결 부탁드려요.

**Comment by seulg2027** [comment]
Navbar 이슈,,
#31 
`Swiper` 에서 사용한 이미지가 네브바 위로 덮어 씌워지는 이슈입니다.
[참고 문서](https://joyful-development.tistory.com/17) 여기를 참고해서 transform 스타일을 줘봤는데도 해결이 되지 않습니다.
일단 열심히 해결해보겠습니다ㅠ_ ㅜ

**Comment by seulg2027** [comment]
네브바 이슈 해결했습니당
